services:

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  payment-service:
    build:
      context: ./payment-service

    container_name: payment-service

    env_file:
      - ./payment-service/.env.docker

    ports:
      - "5000:5000"

    depends_on:
      - kafka
    restart: unless-stopped
  notification-service:
    build:
      context: ./notification-service

    container_name: notification-service

    env_file:
      - ./notification-service/.env.docker

    depends_on:
      - kafka
    restart: unless-stopped
  
  analytics-service:
    build:
      context: ./analytics-service

    container_name: analytics-service

    env_file:
      - ./analytics-service/.env.docker

    ports:
      - "5001:5001"

    depends_on:
      - kafka
    restart: unless-stopped
  webhook-service:
    build:
      context: ./webhook-service

    container_name: webhook-service

    env_file:
      - ./webhook-service/.env.docker

    ports:
      - "5002:5002"

    depends_on:
     - kafka
    restart: unless-stopped
